### PR TITLE
Add reachability to the watchlist succ. gen

### PR DESCRIPTION
**Pull request by tobyodavies**
Watchlists excel at fixpoint computations, the reason I wrote them originally was efficient reachability tests, which I've implemented in this PR.

Also I fixed some bugs with the FD preprocessor input parser.

### CODE REVIEW

**Comment by miquelramirez** [comment]
Thanks for this Toby. I was left wondering back in July what you were after. I am seeing some really hot C++ programming in there. Thanks as well for the FD parsing thing, that will come very in handy, I guess, even if I am not really working much on classical planning these days. 

I've got some questions:

+ How do you keep the watch list along the search path in an efficient manner when you are doing best first search? Is this data structure being constructed for each node in the search and then thrown away?

+ I don't see support for conditional effects - I'd advise that an exception is raised whenever someone tries to use this on a grounded PDDL instance with conditional effects.

Cheers,

Miquel.

**Comment by tobyodavies** [comment]
Yep conditional effect support is something I need to test some
alternatives for.

The nice property of watchlists is that backtracking is a noop, so the
watchlist is always in a valid state for computing reachability of any
state, so you construct the successor generator once, and then test
reachability as many times as you want. Nir has pushed an example. There
are of course potential optimisations if this successor generator is used
in a depth-first search, I will implement this when I implement IDA* in the
next month or two.

**Comment by miquelramirez** [comment]
Yes, in a Dfs derived algorithm I can see that. But I was actually wondering about a BrFS derived one, like Greedy Best First search or WA *

**Comment by miquelramirez** [comment]
On those ones, there's no notion of backtracking, but actually switching from branch to branch (the worse is the heuristic, the more switching).

**Comment by tobyodavies** [comment]
Nothing special needs to be done, reachability will always work, but the
optimizations I have not yet implemented wouldn't be applicable.

**Comment by tobyodavies** [comment]
You cab always treat it as backtracking to the root and triggering all the
watchers for everythjng in that states fluent_vec

**Comment by miquelramirez** [comment]
And doing all those edits is going to pay off? Maybe... Planning problems
in the benchmarks have very few vars, compared to interesting Cnf theories.

**Comment by tobyodavies** [comment]
In the benchmark I've got it's nearly 2x faster compared to the existing reachability code in a breadth-first search. The thing is that, within a reachability test, an action can never be moved more times than it has preconditions, and once triggered is never re-examined. This is often better than iterating over each action as many times as there would be layers in the RPG.

**Comment by miquelramirez** [comment]
Thanks Toby

**Pull request merged**
